/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.jogorandomjframe;

/**
 *
 * @author bergs
 */
public class JogoPainel extends javax.swing.JPanel {
private javax.swing.ButtonGroup buttonGroup1;
    /**
     * Creates new form JogoPainel
     */
    public JogoPainel() {
    initComponents();
    buttonGroup1 = new javax.swing.ButtonGroup();
        
    buttonGroup1.add(jRadioButton1); // Pedra
    buttonGroup1.add(jRadioButton2); // Papel
    buttonGroup1.add(jRadioButton3); // Tesoura
    
    
    }
    
    public static int randInt(int min, int max) {
    java.util.Random rand = new java.util.Random();
    int randomNum = rand.nextInt((max - min) + 1) + min;
    return randomNum;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        Resultado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Pedra, Papel e Tesoura");

        jRadioButton1.setText("Pedra");
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        jRadioButton2.setText("Papel");
        jRadioButton2.addActionListener(this::jRadioButton2ActionPerformed);

        jRadioButton3.setText("Tesoura");
        jRadioButton3.addActionListener(this::jRadioButton3ActionPerformed);

        jButton1.setText("Jogar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jRadioButton3)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


    int jogador = -1;

    // Pedra = 0
    if (jRadioButton1.isSelected()) {
        jogador = 0;
    }

    // Papel = 1
    else if (jRadioButton2.isSelected()) {
        jogador = 1;
    }

    // Tesoura = 2
    else if (jRadioButton3.isSelected()) {
        jogador = 2;
    }

    int computador = randInt(0, 2);

    String resultado;

    if (jogador == computador) {
        resultado = "Empate!";
    }

    else if ((jogador == 0 && computador == 2) ||
             (jogador == 1 && computador == 0) ||
             (jogador == 2 && computador == 1)) {

        resultado = "Você venceu!";
    }

    else {
        resultado = "Computador venceu!";
    }

    String escolhaComputador = "";

    if (computador == 0) {
        escolhaComputador = "Pedra";
    }

    else if (computador == 1) {
        escolhaComputador = "Papel";
    }

    else {
        escolhaComputador = "Tesoura";
    }

    Resultado.setText(
        "Computador: " + escolhaComputador +
        " | Resultado: " + resultado
    );

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    // End of variables declaration//GEN-END:variables
}
